name: afni

on:
  push:
    paths:
      - recipes/*
      - recipes/afni/*
      - .github/workflows/afni.yml
      - .github/workflows/build.sh

  pull_request:
    paths:
      - recipes/*
      - recipes/afni/*
      - .github/workflows/afni.yml
      - .github/workflows/build.sh

env:
  APPLICATION: afni
  PYTHON_VER: 3.8
  DOCKERHUB_ORG: ${{ secrets.DOCKERHUB_ORG }}
  OS_PASSWORD: ${{ secrets.SWIFT_OS_PASSWORD }}
  OS_PROJECT_ID: ${{ secrets.SWIFT_OS_PROJECT_ID }}
  OS_USERNAME: ${{ secrets.SWIFT_OS_USERNAME }}
  OS_APPLICATION_CREDENTIAL_ID: ${{ secrets.SWIFT_OS_APPLICATION_CREDENTIAL_ID }}
  OS_APPLICATION_CREDENTIAL_SECRET: ${{ secrets.SWIFT_OS_APPLICATION_CREDENTIAL_SECRET }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VER }}
      - name: Log into Github Package registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
      - name: Log into Dockerhub (optional)
        if: env.DOCKERHUB_ORG != ''
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Setup Singularity 
        run: bash .github/workflows/setup_singularity.sh
      - name: Log into Singularity Hub
        run: echo "${{ secrets.SINGULARITY_REMOTE_LOGIN }}" | singularity remote login
      - name: Run Recipe and Image builder
        run: bash .github/workflows/build.sh
