name: Docker Image CI

on:
  push:
    branches: [ github-ci ]
  pull_request:
    branches: [ github-ci ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          dockerfile: itksnap/Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: vnmd/itksnap_3.8.0
          tags: latest
