name: itksnap CI

on:
  push:
    paths:
      - itksnap/*
      - .github/workflows/docker-image.yml
  pull_request:
    paths:
      - itksnap/*
      - .github/workflows/docker-image.yml

env:
  DOCKERFILE: itksnap/Dockerfile
  IMAGENAME: itksnap_3.8.0:latest
  IMAGEID: docker.pkg.github.com/neurodesk/caid/itksnap_3.8.0:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Testing
        run: echo "IMAGEID=docker.pkg.github.com/${{ github.repository }}/${{ env.IMAGENAME }}"
