name: Docker Image CI

on:
  push:
    branches: [ github-ci ]
  pull_request:
    branches: [ github-ci ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file itksnap/Dockerfile --tag itksnap:$(date +%s)
