name: freesurfer

on:
  push:
    paths:
      - recipes/freesurfer/*
      - .github/workflows/freesurfer.yml

  pull_request:
    paths:
      - recipes/freesurfer/*
      - .github/workflows/freesurfer.yml

env:
  APPLICATION: freesurfer
  PYTHON_VER: 3.8
  DOCKERHUB_ORG: ${{ secrets.DOCKERHUB_ORG }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VER }}
      - name: Log into Github Package registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
      - name: Log into Dockerhub (optional)
        if: env.DOCKERHUB_ORG != ''
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Run Recipe and Image builder
        run: bash .github/workflows/build.sh
