name: itksnap CI

on:

  push:
    paths:
      - itksnap/*
      - .github/workflows/itksnap.yml
  pull_request:
    paths:
      - itksnap/*
      - .github/workflows/itksnap.yml

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
    - run: IMAGE_ID=docker.pkg.github.com/neurodesk/caid/itksnap_3.8.0
    - run: docker pull $IMAGE_ID || true
    - run: docker build . --file itksnap/Dockerfile --tag $IMAGE_ID --cache-from $IMAGE_ID
    - run: docker push $IMAGE_ID || true