name: itksnap CI

on:

  push:
    paths:
      - itksnap/*
      - .github/workflows/itksnap.yml
  pull_request:
    paths:
      - itksnap/*
      - .github/workflows/itksnap.yml

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Github Package Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
    - name: Build image
      run: |
        IMAGE_ID=docker.pkg.github.com/neurodesk/caid/itksnap_3.8.0:latest
        echo IMAGE_ID=$IMAGE_ID
        docker pull $IMAGE_ID
        docker build . --file itksnap/Dockerfile --tag $IMAGE_ID
